### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by rliaudat** [CodeOTR/flutter-fast-guide#1]
Hi guys, I am following these steps:
1. Create a new folder
2. Open folder with VScode
3. Activate fast_cli
4. fast app -n my_app and enter. I am getting the following error message:
Creating app my_app......
Unhandled exception:
ProcessException: El sistema no puede encontrar el archivo especificado.

  Command: flutter create my_app --empty --org com.example
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      CreateApp.run (package:flutter_fast_cli/src/commands/create_app/create_app.dart:77:19)
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#7      new Future.sync (dart:async/future.dart:305:31)
#8      CommandRunner.run (package:args/command_runner.dart:122:14)
#9      main (file:///C:/Users/rliaudat/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_fast_cli-1.0.5/bin/fast.dart:11:7)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
Creating app my_app......
Unhandled exception:
ProcessException: El sistema no puede encontrar el archivo especificado.

  Command: flutter create my_app --empty --org com.example
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      CreateApp.run (package:flutter_fast_cli/src/commands/create_app/create_app.dart:77:19)
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#7      new Future.sync (dart:async/future.dart:305:31)
#8      CommandRunner.run (package:args/command_runner.dart:122:14)
#9      main (file:///C:/Users/rliaudat/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_fast_cli-1.0.5/bin/fast.dart:11:7)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

Not sure why this is not working.

**Comment by jtmuller5** [comment]
Hi, did you activate the package from pub.dev? I can do some troubleshooting today

**Comment by jtmuller5** [comment]
Are you on a Mac or Windows?

**Comment by jtmuller5** [comment]
I just push a fix that should make the CLI run properly on windows. If you reactivate it  (v 1.0.6) and try again it should work. Let me know!

**Comment by rliaudat** [comment]
Ok I will try and let you know.

Tks for your quick responde.

**Comment by rliaudat** [comment]
Hi guys, so far so good. I have just need to adjust the app name and run it
but everything seems to be created ok.

I will complete by tomorrow and provide you feedback if anything is missing
Great work!
